apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mcp-worker
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
